include::attributes-generic.adoc[]
include::attributes-product.adoc[]

[[cha-containers-support]]
== Compatibility and support conditions

[[sec-sle-container-support-matrix]]
=== Support information

The term "support" refers to two distinct concepts: a) technical enablement of a feature or combination of, for example, host and container, and b) enterprise support as delivered by {suse} to {suse} customers. Enterprise support requires a subscription for {suse} products according to https://www.suse.com/products/terms_and_conditions.pdf. Technical enablement is described below.

[[sec-sle-container-non-sle-host-support]]
==== Support for {slsa} hosts

Consult the following support and compatibility matrix to make sure that the desired host system and container combination is compatible and supported.

.Support matrix
[cols="^,^,^",options="header",]
|===
|Host &#8595; Container image &#8594; |{slsa} 12 |{slsa} 15
|*{slsa} 12 SP5* |&#10003; |&#10059;
|*{slsa} 15* |&#10003; |&#10003;
|*{slea} Micro* |&#10003; |&#10003;
|===

&#10003; Fully supported

&#10059; Limited support (see the Limited support note)

[IMPORTANT]
.Limited support note
====
{suse} provides limited support for {slsa} PRODUCT-GA-based containers running on {slsa} 12 SP5 hosts due to the fact that containerized applications can make system calls not available in the host's kernel. To avoid potential risks and compatibility problems, {suse} recommends using the same Service Pack release for both containers and hosts.
====

BCIs support the following architectures: X86-64, AARCH64, POWER, and ZSERIES. Container architecture must match the architecture of the host. Mismatching container and host scenarios are not supported.

In most scenarios, all SLEA containers are expected to be interoperable if the application or its dependencies do not interact directly with kernel version-specific data structures (`ioctl`, `/proc`, `/sys`, `routing`, `iptables`, `nftables`, `eBPF`, etc.) or modules (KVM, OVS, SystemTap, etc.). Support for `ioctl` and access to `/proc` is limited to the most common scenarios needed by unprivileged users.

[[sec-sle-container-sle-host-support]]
==== Support for non-{slsa} hosts

While {suse}-based containers are fully supported, issues in the host environment must be handled by the host environment vendor. {suse} supports components that are part of the {suse} base containers. Packages from {suse} repositories are also supported. Additional components and applications in the containers are not covered by {suse} support. A {slea} subscription is required for building derived containers.

Containers based on {slsa} 12 SP5 and {slsa} 15 (all service packs) are supported according to their official lifecycles and the following table.

*The following third-party container host platforms are supported.*

.Support for non-SLES hosts
[cols="^,^,^",options="header",]
|===
|Container host platform |Container runtime |Support status
|*{rh} OpenShift* |cri-o |&#10003;
|*Microsoft Azure Kubernetes Service (AKS)* |containerd |&#10003;
|*Google Kubernetes Engine (GKE)* |containerd |&#10059;
|*Amazon Elastic Container Service for Kubernetes (EKS)* |containerd |&#10003;
|===

&#10003; Fully compatible and fully supported

&#10059; Workload specific: fully supported but compatibility depends on type of container (privileged or
unprivileged) and on the application interactions (direct with kernel-version-specific data structures,
kernel-version-specific modules, etc.)

[[sec-sle-container-support-plans]]
=== Support plans

There are three guiding principles of {suse} container support.

[arabic]
. The container image lifecycle follows the lifecycle of the related products.
+
For example, {slsa} {productnumber} container images follow the {slsa} {productnumber} lifecycle.
. Container release status also matches the status of the related product.
+
For example, if {slsa} {productnumber} is in Alpha, Beta, RC, or GA stage, the related containers have the same release status.
. Containers are built using the packages from the related products.
+
For example, {slsa} {productnumber} container images are built using the same packages as the main {slsa} {productnumber} release.

For further information, refer to the https://www.suse.com/lifecycle[Product Support Lifecycle] page and the documentation available for specific container images on https://registry.suse.com[{suse} Registry].

Container images can have different support status, and they can have limited support. Refer to the appropriate https://registry.suse.com[{suse} Registry] page for the further information about a specific container image.

[[sec-supported-containers-hosts]]
=== Containers and host environments support overview

The following support options are valid for {slsa} containers on {suse} host environments.

Containers and host environments delivered by {suse} are fully supported. This also applies to all products under support, including both general support and https://www.suse.com/products/long-term-service-pack-support/[Long Term Service Pack Support] (LTSS).

Partner containers and host environments with a joint engineering collaboration agreement are fully supported. This applies to both the container and host environment as well as all products under support (both general and LTSS) covered by the agreement.

While {suse}-based containers are fully supported, issues in the host environment must be handled by the host environment vendor. {suse} supports components that come from the {suse} base containers. Packages from {suse} repositories are also supported. Additional components and applications in the containers are not covered by {suse} support. No subscription is required for building derived containers based on the content of the BCIs or the BCI Repository. To build containers that include packages from the full {slea} universe, you need a subscription that grants you access to the repositories containing these packages.

Any container and host environment not mentioned above has limited support. Details can be discussed with the {suse} Support Team, who might triage the issue and recommend alternative solutions. In any other case, issues in the host environment must be handled by the host environment vendor.

[[sec-tech-previews]]
=== Technology previews

Container images labeled as Tech Preview are provided by {suse} to give you an opportunity to test new technologies within your environment and share your feedback. If you test a technology preview, contact your {suse} representative to share your experiences and use cases. Your input is helpful for future development.

Technology previews come with the following limitations:

* Technology previews can be functionally incomplete, unstable, and not suitable for production use.
* Technology previews are not supported.
* Technology previews can be available only for specific hardware architectures.
* Specifics and functionality of technology previews are subject to change. As a result, upgrading to subsequent releases of a technology preview may not be possible and may require a fresh installation.
* Technology previews can be canceled at any time. For example, if {suse} discovers that a preview does not meet the customer or market needs, or it does not comply with enterprise standards. {suse} does not commit to providing a supported version of such technologies in the future.

Container images are labeled as `Tech Preview` and are marked as such at https://registry.suse.com[registry.suse.com]. Additionally, container images that are technology previews include the `com.suse.supportlevel="techpreview"` label in the container image metadata. You can check whether the metadata includes the label using the `docker inspect` command, or an appropriate command in other container runtimes.
