include::generic-attributes.adoc[]
include::product-attributes.adoc[]

[[helm-event-pruning]]
== Configuring event pruning

The event pruning feature allows administrators to manage how long registered events are stored in the database and how often the expired events are removed.

The following configuration options are available:

`pruneEventsOlderThan`::
The number of days registered events are stored in the database. The default value is *10*. _Keep in mind that `pruneEventsOlderThan` can be set to *0*. However, this deletes all events whenever the cron job runs, making it impossible to analyze and troubleshoot issues with the application_

`pruneEventsCronjobSchedule`::
The frequency of the cron job that deletes expired events. The default value is *"0 0 * * *"*, which runs daily at midnight.

To modify the default values, execute the following Helm command:

[source,bash]
----
helm ... \
    --set trento-web.pruneEventsOlderThan=<<EXPIRATION_IN_DAYS>> \
    --set trento-web.pruneEventsCronjobSchedule="<<NEW_SCHEDULE>>"
----

Replace the placeholders with the desired values:

`EXPIRATION_IN_DAYS`::
Number of days to retain events in the database before pruning.

`NEW_SCHEDULE`::
The cron rule specifying how frequently the pruning job is performed.

*Example* command to retain events for 30 days and schedule pruning daily at 3 AM:

[source,bash]
----
helm upgrade \
  --install trento-server oci://registry.suse.com/trento/trento-server \
  --set trento-web.trentoWebOrigin=TRENTO_SERVER_HOSTNAME \
  --set trento-web.adminUser.password=ADMIN_PASSWORD \
  --set trento-web.pruneEventsOlderThan=30 \
  --set trento-web.pruneEventsCronjobSchedule="0 3 * * *"
----