include::product-attributes.adoc[]

[[sec-activity-log]]
== Activity Log
:revdate: 2025-06-10


{trento} collects system events and user actions in the Activity Log.
It can be accessed from the left-hand side panel of the {trento}
console.

Each entry in the Activity Log includes the following:

* A timestamp: the day and time (server time, not browser time) the
system event or the user action occurred
* A message: type of the occurred event or user action
* The user that triggered the event or performed the action. User system
is used for events triggered by the system itself.
* Severity status (Info, Warning, and Critical are selected by default)

Clicking on the chevron icon in the activity log entry opens a modal
window containing the activity metadata.

It is possible to search the activity metadata of the activity log entries. You
can use wildcards as well as the OR and AND logical operators for advanced
search queries. The OR operator is applied by default, meaning that a query like
`term1 term2 term3` is treated as `term1 OR term2 OR term3`. You can combine
multiple logical operators, keeping in mind that they are parsed from left to
right.

The Activity Log allows you to filter by the type of event or user action
(commonly referred to as resource type), by the user that triggered the event or
performed the action, and by severity status. Only active users are available
for filtering. The Activity Log also allows you to filter out entries that are
newer and/or older than an specific date and time (server time).

Once a filter has been set, click Apply to filter out the undesired
entries and Reset to remove all the filters.

Entries related to user management can only be displayed by users that
have the `+all:all+` or `+all:users+` permissions. This includes the
following:

* Login attempts
* User creations
* User modifications
* User deletions
* Profile updates

The Activity Log features a privacy-related access level controlled through the
_activity_log:users_ permission. For users without this permission, user-related
info in the Activity Log is redacted. Unprivileged users can only see their own
user names as well as user system.

Entries in the Activity Log are sorted from newer to older. Click **Refresh** to
update the Activity Log view with entries generated since they accessed the view
or after the last refresh. You can also enable the auto-refresh feature by
selecting the desired auto-refresh interval.

The pagination features at the bottom of the Activity Log allow you to
specify the number of entries to display in a page, go to the next or
previous page of the view, and jump to the last page and back to first
one.

The default retention time for entries in the Activity Log is one month.
This can be changed in the Activity Log section under Settings. Changing
the retention time requires the `+all:settings+` permissions. Entries
older than the specified retention time are deleted every day at
midnight (server time).
