include::product-attributes.adoc[]

[[sec-activity-log]]
== Activity Log

{trento} collects system events and user actions in the Activity Log.
It can be accessed from the left-hand side panel of the {trento}
console.

Each entry in the Activity Log includes the following:

* A timestamp: the day and time (server time, not browser time) the
system event or the user action occurred
* A message: type of the occurred event or user action
* The user that triggered the event or performed the action. User system
is used for events triggered by the system itself.

Clicking on the chevron icon in the activity log entry opens a modal
window containing the activity metadata.

The Activity Log allows to filter by the type of event or user action
(commonly referred to as resource type) and by the user that triggered
the event or performed the action. Only active users are available for
filtering. The Activity Log also allows you to filter out entries that
are newer and/or older than an specific date and time (server time).

Once a filter has been set, click Apply to filter out the undesired
entries and Reset to remove all the filters.

Entries related to user management can only be displayed by users that
have the `+all:all+` or `+all:users+` permissions. This includes the
following:

* Login attempts
* User creations
* User modifications
* User deletions
* Profile updates

Entries in the Activity Log are sorted from newer to older. Click
Refresh to update the Activity Log view with entries generated since
they accessed the view or after the last refresh

The pagination features at the bottom of the Activity Log allow you to
specify the number of entries to display in a page, go to the next or
previous page of the view, and jump to the last page and back to first
one.

The default retention time for entries in the Activity Log is one month.
This can be changed in the Activity Log section under Settings. Changing
the retention time requires the `+all:settings+` permissions. Entries
older than the specified retention time are deleted every day at
midnight (server time).
