include::generic-attributes.adoc[]
include::product-attributes.adoc[]

[[sec-trento-problemanalysis]]
== Problem Analysis

This section covers common problems and how to analyze them.

=== {trserver}

There are two tools you can use to analyze issues with {trserver} in a
{k8s} scenario. These tools collect information and data that can be
useful when troubleshooting and analyzing the issue.

==== {trento} Support Plugin

The {trento} support plugin automates the collection of logs and
relevant runtime information on the server side. Using the plugin
requires a host with the following setup:

* The packages jq and python3-yq are installed.
* Helm is installed.
* The command `+kubectl+` is installed and connected to the {k8s}
cluster where {trserver} is running.

To use the plugin, proceed as follows:

. Download the {trento} support plugin script:
+
====
[source,subs="attributes"]
----
{prompt_root}wget https://raw.githubusercontent.com/trento-project/support/refs/heads/main/trento-support.sh
----
====
+
[NOTE]
.Package available in {sles4sap} 15 SP3 and higher
====
Customers of {sles4sap} 15 SP3 and higher can install the
trento-supportconfig-plugin package directly from the official
{sles4sapa} 15 repos using {zypper}. The Containers Module is required
for installation.
====
. Make the script executable:
+
====
[source,subs="attributes"]
----
{prompt_root}chmod +x trento-support.sh
----
====
+
. Make sure that `+kubectl+` is connected to the {k8s} cluster where
{trserver} is running and execute the script:
+
====
[source,subs="attributes"]
----
{prompt_root}./trento-support.sh --output file-tgz --collect all
----
====
+
. Send the generated archive file to support for analysis.

The {trento} support plugin accepts the following options:

`+-o+`, `+--output+`::
  Output type. Options: stdout|file|file-tgz
`+-c+`, `+--collect+`::
  Collection options: configuration|base|kubernetes|all
`+-r+`, `+--release-name+`::
  Release name to use for the chart installation. "trento-server" by
  default.
`+-n+`, `+--namespace+`::
  {kube} namespace used when installing the chart. "default" by
  default.
`+--help+`::
  Shows help messages

==== Scenario dump

The scenario dump is a dump of the {trento} database. It helps the
{trento} team to recreate the scenario to test it. Using the script
that generates the dump requires a host with the following setup:

* The command `+kubectl+` is installed and connected to the {k8s}
cluster where {trento} Server is running.

To generate the dump, proceed as follows:

. Download the latest version of the dump script:
+
====
[source,bash,subs="attributes"]
----
{prompt_user}wget https://raw.githubusercontent.com/trento-project/web/main/hack/dump_scenario_from_k8.sh
----
====
+
. Make the script executable:
+
====
[source,bash,subs="attributes"]
----
{prompt_user}chmod +x dump_scenario_from_k8.sh
----
====
+
. Make sure that `+kubectl+` is connected to the {k8s} cluster where
{trserver} is running and execute the script as follows:
+
====
[source,bash,subs="attributes"]
----
{prompt_user}./dump_scenario_from_k8.sh -n SCENARIO_NAME -p PATH
----
====
+
. Go to `+/scenarios/+`, collect all the JSON files and send them to
support for analysis.

==== Pods descriptions and logs

In addition to the output of the {trento} Support Plugin and the Dump
Scenario script, the descriptions and logs of the {trserver} pods can
be useful for analysis and troubleshooting purposes. These descriptions
and logs can be easily retrieved with the `+kubectl+` command. For this
to work, you need a host where kubectl is installed and connected to the
{k8s} cluster running {trserver}.

. List the pods running in {k8s} cluster and their statuses.
{trserver} currently consists of the following six pods:
+
====
[source,bash,subs="attributes"]
----
{prompt_user}kubectl get pods
trento-server-prometheus-server-*
trento-server-postgresql-0
trento-server-web-*
trento-server-wanda-*
trento-server-rabbitmq-0
----
====
+
. Retrieve the description of a pod as follows:
+
====
[source,bash,subs="attributes"]
----
{prompt_user}kubectl describe pod POD_NAME
----
====
+
. Retrieve the log of a pod as follows:
+
====
[source,bash,subs="attributes"]
----
{prompt_user}kubectl logs POD_NAME
----
====
+
. Monitor the log of a pod as follows:
+
====
[source,bash,subs="attributes"]
----
{prompt_user}kubectl logs POD_NAME --follow
----
====

=== {tragent}

The first source to analyze issues with the {tragent} is the {tragent}
status. It can be retrieved as follows:

====
[source,bash,subs="attributes"]
----
{prompt_sudo}systemctl status trento-agent
----
====

If further analysis is required, activate debug log level for the agent.
A detailed log can be then retrieved from the journal:

. Add parameter `+log-level+` with value `+debug+` to the
`+/etc/trento/agent.yaml+` configuration file.
+
====
[source,bash,subs="attributes"]
----
{prompt_sudo}vi /etc/trento/agent.yaml
----
====
+
. Add the following entry:
+
====
[source,bash]
----
log-level: debug
----
====
+
. Restart the agent:
+
====
[source,bash,subs="attributes"]
----
{prompt_sudo}systemctl restart trento-agent
----
====
+
. Retrieve the log from the journal:
+
====
[source,bash,subs="attributes"]
----
{prompt_sudo}journalctl -u trento-agent
----
====
