== Improving the documentation

Feedback and contributions to this documentation can be submitted using any of the following options.

Service requests and support::
  For services and support options available for your product, see https://www.suse.com/support/.
  To open a service request, you need a SUSE subscription registered at {scc}. Go to https://scc.suse.com/support/requests, log in, and click _Create New_.
Bug reports::
  Report issues with the documentation at https://bugzilla.suse.com/. To simplify the process, click the _Report an issue_ icon in the HTML version of this document. This preselects the right product and category in Bugzilla and adds a link to the current section. You can now write your bug report.
  A Bugzilla account is required.
Contributions::
  To contribute to this documentation, click the _Edit source document_ icon in the HTML version of this document. This will take you to the source code on GitHub, where you can open a pull request.
  A GitHub account is required.

[NOTE]
.Edit source document only available for English
====
The _Edit source document_ icons are only available for the English version of each document. For all other languages, use the _Report an issue_ icons as described above.
====

For more information about the documentation environment used for this documentation, refer to the repository's _README_ file at https://github.com/SUSE/doc-unversioned/blob/main/README.adoc

Mail::
  You can also report errors and send feedback concerning the documentation to doc-team@suse.com. Include the document title, the product version, and the publication date of the document. Additionally, include the relevant section number and title (or provide the URL), and provide a concise description of the problem.

