include::attributes-generic.adoc[]
include::attributes-product.adoc[]

[[cha-verify-containers]]
== Verifying container images

Verifying container images allows you to confirm their provenance, thus ensuring
the supply chain security. This chapter provides information on signing and
verifying container images.

[[sec-verify-docker]]
=== Verifying {bcia} with Docker
Signatures for images available through {suseregistry} are stored in the Notary. You can verify the
signature of a specific image using the following command:

....
docker trust inspect --pretty registry.suse.com/suse/IMAGE:TAG
....

For example, the command `docker trust inspect --pretty
   registry.suse.com/suse/sle15:latest` verifies the signature of the latest SLE15 base image.

To automatically validate an image when you pull it, set the environment `DOCKER_CONTENT_TRUST` to `1`. For example:

....
env DOCKER_CONTENT_TRUST=1 docker pull registry.suse.com/suse/sle15:latest
....

[[sec-verify-cosign]]
=== Verifying {bcia} with Cosign

To verify a {bcia} image, run Cosign in the container. The command below fetches the
signing key from the SUSE server and uses it to verify the latest BCI-Base container
image.

[source,ShellSession]
----
> podman run --rm -it gcr.io/projectsigstore/cosign verify \
    --key https://ftp.suse.com/pub/projects/security/keys/container–key.pem \
    registry.suse.com/bci/bci-base:latest | tail -1 | jq

[
  {
    "critical": {
      "identity": {
        "docker-reference": "registry.suse.com/bci/bci-base"
      },
      "image": {
        "docker-manifest-digest": "sha256:52a828600279746ef669cf02a599660cd53faf4b2430a6b211d593c3add047f5"
      },
      "type": "cosign container image signature"
    },
    "optional": {
      "creator": "OBS"
    }
  }
]
----

The signing key can be used to verify all {bcia} container images. The signing
key ships with {sle} 15 (the `/usr/share/container-keys/suse-container-key.pem` file).

You can also check {bcia} container images against
https://github.com/sigstore/rekor[rekor], the immutable tamper resistant
ledger. For example:

[source,ShellSession]
----
> podman run --rm -it -e COSIGN_EXPERIMENTAL=1 gcr.io/projectsigstore/cosign \
    verify --key https://ftp.suse.com/pub/projects/security/keys/container–key.pem \
    registry.suse.com/bci/bci-base:latest | tail -1 | jq
[
  {
    "critical": {
      "identity": {
        "docker-reference": "registry.suse.com/bci/bci-base"
      },
      "image": {
        "docker-manifest-digest": "sha256:52a828600279746ef669cf02a599660cd53faf4b2430a6b211d593c3add047f5"
      },
      "type": "cosign container image signature"
    },
    "optional": {
      "creator": "OBS"
    }
  }
]
----

If verification fails, the output of the `cosign verify` command is similar to the one below.

----
Error: no matching signatures:
crypto/rsa: verification error
main.go:62: error during command execution: no matching signatures:
crypto/rsa: verification error
----

[[sec-verify-podman]]
== Verifying {bcia} with {podman}

Verifying {bcia}s using {podman} is a three-step process. First, specify
`registry.suse.com` as the registry for image verification.

{{< hint type="note" >}}
Skip this step on SLE or openSUSE, as the correct configuration is already in place.
{{< /hint >}}

To do this, add the following configuration to
`/etc/containers/registries.d/default.yaml`:

[source,YAML]
----
docker:
  registry.suse.com:
    use-sigstore-attachments: true
----

Instead of editing the `default.yaml`, you can create a new file in
`/etc/containers/registries.d/` with a filename of your choice.

Next, modify the
https://github.com/containers/image/blob/main/docs/containers-policy.json.5.md[/etc/containers/policy.json]
file. Under the `docker` attribute, add the `registry.suse.com` configuration
similar to the following:

[source,json]
----
{
  "default": [
    {
      "type": "insecureAcceptAnything"
    }
  ],
  "transports": {
    "docker-daemon": {
      "": [
        {
          "type": "insecureAcceptAnything"
        }
      ]
    },
    "docker": {
      "registry.suse.com": [
        {
          "type": "sigstoreSigned",
          "keyPath": "/usr/share/pki/containers/suse-container-key.pem",
          "signedIdentity": {
            "type": "matchRepository"
          }
        }
      ]
    }
  }
}
----

The specified configuration instructs {podman}, {skopeo} and {buildah} to verify
images under the `registry.suse.com` repository. This way,{podman} checks the
validity of the signature using the specified public key before pulling the
image. It rejects the image if the validation fails.

{{< hint type="note" >}}
Do not remove existing entries in `transports.docker`. Append the entry for `registry.suse.com` to the list.
{{< /hint >}}

Fetch the public key used to sign {bcia}s from https://www.suse.com/support/security/keys/[SUSE Signing Keys], or use the following command:

[source,ShellSession]
----
> sudo curl -s https://ftp.suse.com/pub/projects/security/keys/container–key.pem \
    -o /usr/share/pki/containers/suse-container-key.pem
----

{{< hint type="note" >}}
This step is optional on {sle}. The signing key is already available in `/usr/share/pki/containers/suse-container-key.pem`.
{{< /hint >}}

{buildah}, {podman} and {skopeo} will automatically verify every image pulled
from `registry.suse.com` from now on. There are no additional steps required.

If verification fails, the command returns an error message as follows:
[source,ShellSession]
----
> podman pull registry.suse.com/bci/bci-base:latest
Trying to pull registry.suse.com/bci/bci-base:latest...
Error: copying system image from manifest list: Source image rejected: Signature for identity registry.suse.com/bci/bci-base is not accepted
----

If there are no issues with the signed image and your configuration, you can proceed with using the container image.