include::attributes-generic.adoc[]
include::attributes-product.adoc[]

[[cha-containers-tools]]
== Tools for building images and managing containers

This chapter provides a brief overview of tools, provided by SUSE, for building, running and
managing containers. The frontier between building, running and managing is sometimes pretty thin,
thus some tools are not exclusively targeting a topic and might be able to fulfill multiple roles.

This article is not an exhaustive list of all available tools, but rather tries to provide you with
a better understanding of which tools fits where and how you can combine them together.

All our tools mentioned below are part of the *{sles} {productnumber} Containers Module*, except
the https://openbuildservice.org[Open Build Service]. You can see the full list of packages in the
*Containers Module* in the https://scc.suse.com/packages[{scc}].

[[sec-tools-suse-registry]]
=== {suseregistry}

https://registry.suse.com is the only source for official SUSE base container images.
It contains tested, up to date and certified {slea} base container images. All images in the
{suseregistry} undergo a maintenance process. The images are built to contain the latest available
updates and fixes. The {suseregistry}'s Web user interface lists a subset of the available images:
Base Container Images, Language Container Images, Application Container Images, SUSE Linux
Enterprise Server Images and Releases Out of General Support.
The Web UI also provide more details to any given images, like release date, support level, size,
digest of the images and packages inside the image.

[[sec-tools-docker]]
=== {docker}

{docker} is a popular system for creating and managing containers. Its core is the
https://github.com/moby/moby[{docker} Open Source Engine&#8212;]a lightweight virtualization
solution to run containers simultaneously on a single host. {docker} containers are be built using
Dockerfiles.

[[sec-tools-podman]]
=== {podman}

https://podman.io[{podman}] stands for Pod Manager tool. It is a daemonless container engine for
developing, managing, and running
https://opencontainers.org/about/overview/[Open Container Initiative (OCI)] containers on a Linux
system, and it offers a drop-in alternative for {docker}. {podman} is the recommended container
runtime for {slesa}.
For a general introduction to {podman}, refer to <<cha-podman-overview>>.

[[sec-tools-buildah]]
=== {buildah}

https://buildah.io[{buildah}] is an utility for building OCI container images. It is a complementary
tool to {podman}, and actually `podman build` uses {buildah} to perform container image builds.
{buildah} makes it possible to build images from scratch, from existing images, and using
Dockerfiles. OCI images built using the {buildah} command-line tool and the underlying OCI-based
technologies (for example, `containers/image` and `containers/storage` ) are portable and can
therefore run in a {deng} environment.
For information on installing and using {buildah}, refer to <<cha-buildah-overview>>.

[[sec-tools-skopeo]]
=== {skopeo}

https://github.com/containers/skopeo[{skopeo}] is a command-line utility for coping, inspecting,
deleting and signing on container images and image repositories. {skopeo} is able to inspect
containers and repositories on remote or local container registries. {skopeo} can copy container
images between different storage mechanisms. {skopeo} is part of the `Basesystem Module` of SLES.

[[sec-tools-helm]]
=== {helm}

https://helm.sh[{helm}] is the Kubernetes Package Manager, it's the de-facto standard to deploy
containerized applications on Kubernetes clusters, via `charts`.
It is able to install/update/uninstall applications on a single or multiple containers and the
associated resources, like configuration, storage volumes, etc.
For instance, It is used for instance to deploy our RMT server, refers to our
https://documentation.suse.com/sles/15-SP4/single-html/SLES-rmt/index.html#sec-rmt-deploy-kubernetes[RMT documentation]
for more information.

[[sec-tools-distribution]]
=== {distribution}

https://github.com/distribution/distribution[Distribution] is an Open Source Registry implementation
for storing and distributing container images using the OCI Distribution Specification. It is the
core for many registry operators including Docker Hub, GitHub Container Registry, GitLab Container
Registry, CNCF Harbor Project, etc.
It's a toolset to provide a simple, secure, and scalable base for building a large scale registry
solution or running a simple private registry.

[[sec-tools-obs]]
=== Open Build Service

The http://openbuildservice.org[Open Build Service (OBS)] provides free infrastructure for building
and storing RPM packages including various container formats. The
https://registry.opensuse.org[OBS Container Registry] provides a detailed listing of all container
images built by the OBS, complete with commands for pulling the images into your local environment.
The OBS https://build.opensuse.org/image_templates[{opensuse}container image templates] can be
modified to specific needs, which offers the easiest way to create your own container branch.
Container images can be built with native {docker} tools from an existing image using a 
`Dockerfile`. Alternatively, images can be built from scratch using the {kiwi} image-building
solution.

Instructions on how to build images on OBS can be found
https://openbuildservice.org/2018/05/09/container-building-and-distribution/[here].

SUSE Container Images, called SUSE Linux Enterprise Base Container Images ({bcia}) are the only
official SUSE container images,<<cha-bci>>. They are not available at https://build.opensuse.org,
and the RPMs exported there are not identical to the internal ones. This means that it is not
possible to build officially supported images at https://build.opensuse.org.

For more information about {bcia}, refer to <<cha-bci>>.

[[sec-tools-kiwi]]
=== {kiwi}

https://github.com/OSInside/kiwi[{kiwi}] Next Generation is a multi-purpose tool for building
images. In addition to container images, regular installation ISO images, and images for virtual
machines, {kiwi} can build images that boot via PXE or Vagrant boxes. The main building block in
{kiwi} is an image XML description, a directory that includes the `config.xml` or `.kiwi` file along
with scripts or configuration data. The process of creating images with {kiwi} is fully automated
and does not require any user interaction. Any information required for the image creation process
is provided by the primary configuration file `config.xml`. The image can be customized using the 
`config.sh` and `images.sh` scripts. {kiwi} is the core engine of
http://openbuildservice.org[Open Build Service (OBS)].

[NOTE]
====
It is important to distinguish between {kiwi} NG (currently version 9.20.9) and its
unmaintained legacy versions (7.x.x or older), now called
https://documentation.suse.com/kiwi/[{kiwi} Legacy].
====

For specific information on how to install {kiwi} and use it to build images, see the
http://osinside.github.io/kiwi/[{kiwi} documentation]. A collection of example image descriptions
can be found on the https://github.com/OSInside/kiwi-descriptions[{kiwi} GitHub repository].

{kiwi}'s man pages provide information on using the tool. To access the man pages, install the
`kiwi-man-pages`` package.
