include::attributes-generic.adoc[]
include::attributes-product.adoc[]

[[cha-sle-containers-module]]
== SLE Containers Module
As a pre-requisite to work with containers on a SUSE Linux Enterprise Server, you have to enable the {sle-containers-module}. This contains packages revolving around containers, including container engine and core container-related tools like on-premise registry. For more information about SLE Modules please refers to https://documentation.suse.com/sles/15-SP3/html/SLES-all/article-modules.html.

The regular SLES subscription include {sle-containers-module} free of charge.
[[sec-sle-containers-module-yast]]
=== Enabling the Containers Module using the {yast} graphical interface

. Start {yast}, and select _Software > Software Repositories_.
. Click _Add_ to open the add-on dialog.
. Select _Extensions and Modules_ from _Registration Server_ and click _Next_.
. From the list of available extensions and modules, select Containers Module {productnumber} x86_64 and click _Next_. This adds the        _Containers Module_ and its repositories to the system.
. If you use {rmtool}, update the list of repositories on the {rmt} server.

[[sec-sle-containers-module-cli]]
=== Enabling the Containers Module from the command line using {suseconnect}

The _Containers Module_ can also be added with the following command:

....
> sudo SUSEConnect -p sle-module-containers/15.4/x86_64
....

