include::attributes-generic.adoc[]
include::attributes-product.adoc[]

[[cha-orchestration]]
== Container orchestration

[[sec-orchestration-introduction]]
=== Introduction
Now that you have a better understanding of how to handle containers on your desktop or server, we
can go to the next step: How to make use of containers in production?
In a production environment you will likely have to manage multiple containers, be it locally on
your single container host or on multiple Container Host. To manage multiple containers, you will
have to group your containers (one or more) into a Pod, which will allow them to share storage and
network resources but also a specification for how to be deployed and run. In short a pod
encapsulates an application composed of multiple containers into a single unit. The pod concept was
introduced by https://kubernetes.io/docs/concepts/workloads/pods/[Kubernetes] however Podman, which
stand for Pod Manager, uses the same definition as Kubernetes. 

[[sec-orchestration-podman]]
=== Single Container Host with Podman

[[sec-orchestration-architecture]]
==== Architecture
A pod is a group of containers that share the same name space, ports, and network connection.
Usually, containers within one pod can communicate directly with each other. Each pod contains an
infrastructure container (INFRA), whose purpose is to hold the name space. INFRA also enables Podman
to add other containers to the pod. Port bindings, cgroup-parent values, and kernel name spaces are
all assigned to the infrastructure container. Therefore, later changes of these values are not
possible.

Insert https://documentation.suse.com/sle-micro/5.3/single-html/SLE-Micro-podman/images/pods_architecture.svg

Each container in a pod has its own instance of a monitoring program. The monitoring program watches
the container's process and if the container dies, the monitoring program saves its exit code. The
program also holds open the tty interface for the particular container. The monitoring program
enables you to run containers in the detached mode when Podman exits, because this program continues
to run and enables you to attach tty later.

[[sec-orchestration-podman-pod]]
==== Podman pod
podman pod is the command line tool for creating, removing, querying and inspecting pods. You can check all the subcommands of podman pod in the https://docs.podman.io/en/latest/markdown/podman-pod.1.html[official upstream documentation]. 

[[sec-orchestration-pod-create]]
==== Create and list pods
podman pod create will create a pod with a random name, but you can use the --name parameter to
assign the desired name to a pod.

....
 $ sudo podman pod create
344940492c00b6a19ececbc5b109351bf0a3b8b19b3c279a097da7a653c592d0
....

you can list our pods using the podman pod list command:

....
$ sudo podman pod list
POD ID        NAME          STATUS      CREATED        INFRA ID      # OF CONTAINERS
344940492c00  suspicious_curie  Created     2 minutes ago  617d7e3ce399  1
....

Print out information about pods:

....
$ sudo podman ps -a --pod
CONTAINER ID  IMAGE                 COMMAND     CREATED        STATUS      PORTS       NAMES               POD ID        PODNAME
617d7e3ce399  k8s.gcr.io/pause:3.5              5 minutes ago  Created                 344940492c00-infra  344940492c00  suspicious_curie
....

The created pod has an infra container identified by the `k8s.gcr.io` name. The purpose of this
container is to reserve the namespaces associated with the pod and allow {podman} to add other
containers to the pod.

[[sec-orchestration-pod-add]]
==== Run and add a container to a pod
Using the podman run --pod command, you can run a container and add it to the desired pod. For
example, the command below runs a container based on the suse/sle15 image and adds the container to
the `suspicious_curie` pod: 

....
$ sudo podman run -d --pod sweet_liskov registry.suse.com/suse/sle15 sleep 1h
8f5af62a7c385bbd1a3a5cc3a53a8d0f8cf942adc26a065960d4232fcc93ac98
....

WARNING: If this command shows the following warning, please refer
http://https//documentation.suse.com/container/all/single-html/SLES-container/#sec-bci-suseconnect-podman-buildah-nerdctl[Using container-suseconnect on non-SLE hosts or with Podman, Buildah, and nerdctl]: 
....
WARN[0000] Path "/etc/SUSEConnect" from "/etc/containers/mounts.conf" doesn't exist, skipping 
....

The command above adds a container that sleeps for 60 minutes and then exits. Run the podman ps -a
--pod command again and you should see that the pod now has two containers.

You can also check the command podman pod ps:
....
$ sudo podman pod ps
POD ID        NAME          STATUS      CREATED         INFRA ID      # OF CONTAINERS
344940492c00  suspicious_curie Running     21 minutes ago  617d7e3ce399  2
....

[[sec-orchestration-pod-stop]]
==== Stoping pod or a container in a pod
Let's stop our newly created container named objective_jemison

....
$ sudo podman ps -a --pod
CONTAINER ID  IMAGE                                COMMAND     CREATED         STATUS            PORTS       NAMES               POD ID        PODNAME
617d7e3ce399  k8s.gcr.io/pause:3.5                             14 minutes ago  Up 4 minutes ago              344940492c00-infra  344940492c00  suspicious_curie 8f5af62a7c38  registry.suse.com/suse/sle15:latest  sleep 1h    4 minutes ago   Up 4 minutes ago              objective_jemison   344940492c00  suspicious_curie
$ sudo podman stop objective_jemison
objective_jemison
$ sudo podman pod ps
POD ID        NAME          STATUS      CREATED         INFRA ID      # OF CONTAINERS
344940492c00  suspicious_curie  Degraded    25 minutes ago  617d7e3ce399  2
$ sudo podman ps -a --pod
CONTAINER ID  IMAGE                                COMMAND     CREATED         STATUS                       PORTS       NAMES               POD ID        PODNAME
617d7e3ce399  k8s.gcr.io/pause:3.5                             25 minutes ago  Up 15 minutes ago                        344940492c00-infra  344940492c00  suspicious_curie 8f5af62a7c38  registry.suse.com/suse/sle15:latest  sleep 1h    15 minutes ago  Exited (137) 14 seconds ago              objective_jemison   344940492c00  suspicious_curie 
....

You can also stop the pod and all of its containers using, podman pod stop

....
$ sudo podman pod stop suspicious_curie
344940492c00b6a19ececbc5b109351bf0a3b8b19b3c279a097da7a653c592d0
$ sudo podman ps -ap
CONTAINER ID  IMAGE                                COMMAND     CREATED         STATUS                      PORTS       NAMES               POD ID        PODNAME
617d7e3ce399  k8s.gcr.io/pause:3.5                             29 minutes ago  Exited (0) 7 seconds ago                344940492c00-infra  344940492c00  suspicious_curie 8f5af62a7c38  registry.suse.com/suse/sle15:latest  sleep 1h    19 minutes ago  Exited (137) 3 minutes ago              objective_jemison   344940492c00  suspicious_curie
....

Of course you can also start and restart everything with sudo podman start yourcontainername,
 podman pod start yourpodname or podman pod restart yourpodname.

[[sec-orchestreation-podman-systemd]]
==== Creating systemd units for a pod

[[sec-orchestration-podman-more]]
==== More on podman
If you want to learn more on podman and in depth instruction on how to handle pod deployment,
please check https://docs.podman.io/en/latest/ and https://github.com/containers/podman

[[sec-orchestration-kubernetes]]
=== Multi Container Host with Kubernetes

Kubernetes provides a set of functionality that are required to deploy containers at production
level: storage, high availability, lifecycle.
Kubernetes makes multiple machines work together to create a cluster which you will be able to
interact with using an API. The deployment of Kubernetes itself has seen a lot of tools emerge, but
the one we do favour at SUSE is Rancher. Rancher is able to deploy Kubernetes, but also to manage
application running on top of k8s. To be even more precise, a single Rancher setup can manage
multiple Kubernetes cluster, easing the burden of managing the software you deployed just to run you
application.

[[sec-k8s]]
==== Kubernetes (k8s)
[[sec-k3s]]
==== Lightweight Kubernetes (k3s)
https://documentation.suse.com/trd/kubernetes/single-html/kubernetes_ri_rancher-k3s-sles/index.html#id-introduction
