include::attributes-generic.adoc[]
include::attributes-product.adoc[]

[[cha-registration]]
== Registration and Online Repositories

[[sec-sle-containers-module]]
== SLE Containers Module
As a pre-requisite to work with containers on a SUSE Linux Enterprise Server, you have to enable the {sle-containers-module}. This contains packages revolving around containers, including container engine and core container-related tools like on-premise registry. For more information about SLE Modules please refers to https://documentation.suse.com/sles/15-SP3/html/SLES-all/article-modules.html.

The regular SLES subscription include {sle-containers-module} free of charge.

[[sec-sle-containers-module-yast]]
=== Enabling the Containers Module using the {yast} graphical interface

. Start {yast}, and select _Software > Software Repositories_.
. Click _Add_ to open the add-on dialog.
. Select _Extensions and Modules_ from _Registration Server_ and click _Next_.
. From the list of available extensions and modules, select Containers Module {productnumber} x86_64 and click _Next_. This adds the        _Containers Module_ and its repositories to the system.
. If you use {rmtool}, update the list of repositories on the {rmt} server.

[[sec-sle-containers-module-cli]]
=== Enabling the Containers Module from the command line using {suseconnect}

The _Containers Module_ can also be added with the following command:

....
> sudo SUSEConnect -p sle-module-containers/15.4/x86_64
....

[[sec-container-suseconnect]]
== container-suseconnect
[[sec-container-suseconnect-intro]]
=== What is container-suseconnect?

https://github.com/SUSE/container-suseconnect[`container-suseconnect`]
is a plugin available in all Base Container Images that ship with
Zypper. When the plugin detects the host's SUSE Linux Enterprise Server
registration credentials, it uses them to give the container access the
SUSE Linux Enterprise repositories. This includes additional modules and
previous package versions that are not part of the free SLE_BCI
repository.

[[sec-container-suseconnect-sle]]
=== How to use container-suseconnect on SLES and openSUSE

If you are running a registered SLES system with Docker,
`container-suseconnect` automatically detects and uses the subscription,
without requiring any action on your part.

On openSUSE systems with Docker, you must copy the files
`/etc/SUSEConnect` and `/etc/zypp/credentials.d/SCCcredentials` from a
registered SLES machine to your local machine. Note that the
`/etc/SUSEConnect` file is required only if you are using RMT for
managing your registration credentials.

[[sec-container-suseconnect-nonsle]]
=== How to use container-suseconnect on non-SLES hosts or with Podman and Buildah

You need a registered SLES system to use `container-suseconnect` on
non-SLE hosts or with Podman and Buildah. This can be a
physical machine, a virtual machine, or the bci-base container with
`SUSEConnect` installed and registered.

If you do no use RMT, copy `/etc/zypp/credentials.d/SCCcredentials` to the development machine.
Otherwise, copy both the `/etc/zypp/credentials.d/SCCcredentials` and `/etc/SUSEConnect` files.

You can use the following command to obtain `SCCcredentials` (replace
`REGISTRATION_CODE` with your SCC registration code)

....
podman run --rm registry.suse.com/suse/sle15:latest bash -c \
    "zypper -n in SUSEConnect; SUSEConnect --regcode REGISTRATION_CODE; \
     cat /etc/zypp/credentials.d/SCCcredentials"
....

If you are running a container based on a SLE BCI, mount
`SCCcredentials` (and optionally `/etc/SUSEConnect`) in the correct
destination. The following example shows how to mount `SCCcredentials`
in the current working directory:

....
podman run -v /path/to/SCCcredentials:/etc/zypp/credentials.d/SCCcredentials \
    -it --pull=always registry.suse.com/bci/bci-base:latest
....

Do not copy the `SCCcredentials` and `SUSEConnect` files into the
container image to avoid inadvertently adding them to the final image.
Use secrets instead, as they are only available to a single layer and
are not part of the built image. To do this, put a copy of
`SCCcredentials` (and optionally `SUSEConnect`) somewhere on the file
system and modify the `RUN` instructions that invoke Zypper as follows:

....
FROM registry.suse.com/bci/bci-base:latest

RUN --mount=type=secret,id=SUSEConnect \
    --mount=type=secret,id=SCCcredentials \
    zypper -n in fluxbox
....

Buildah support mounting secrets via the `--secret` flag as follows:

....
buildah bud --layers --secret=id=SCCcredentials,src=/path/to/SCCcredentials \
    --secret=id=SUSEConnect,src=/path/to/SUSEConnect .
....

[NOTE]
.known issue
====
container-suseconnect runs automatically every time you invoke zypper. If you are not using a
registered SLES host, you may see the following error message:

....
> zypper ref
Refreshing service 'container-suseconnect-zypp'.
Problem retrieving the repository index file for service 'container-suseconnect-zypp':
[container-suseconnect-zypp|file:/usr/lib/zypp/plugins/services/container-suseconnect-zypp]
Warning: Skipping service 'container-suseconnect-zypp' because of the above error.
....

Ignore the message, as it simply indicates that container-suseconnect was not able to retrieve your
SUSE Customer Center credentials, and thus could not add the full SLE repositories. You still have
full access to the SLE_BCI repository, and can continue using the container as intended.
====

[[sec-container-suseconnect-modules]]
=== Adding modules into the container or container Image

`container-suseconnect` allows you to automatically add SLE Modules into
a container or container image. What modules are added is determined by
the environment variable `ADDITIONAL_MODULES` that includes a
comma-separated list of the module names. In a `Dockerfile`, this
is done using the `ENV` directive as follows:

....
FROM registry.suse.com/bci/bci-base:latest
ENV ADDITIONAL_MODULES sle-module-desktop-applications,sle-module-development-tools

RUN --mount=type=secret,id=SCCcredentials zypper -n in fluxbox && zypper -n clean
....
